### ISSUE TITLE
A list of IDEs

### ISSUE THREAD

**Issue by lnishan** [lnishan/awesome-competitive-programming#15]
A list of IDEs to be added.

CLI:
* Vim
* Emacs
* Far Manager

GUI:
* Codeblocks
* IntelliJ IDEA
* CLion
* CodeLite
* Geany

(Do people actually use the following for compeititive programming?)
* Visual Studio
* Sublime Text
* Atom

Special Place:
* Orwell Dev-C++  
Seems to be discontinued --- again,  
but many people still like it I think ...

I personally have tried everything on this list (always like to explore new software),
so I think I can say a thing or two about almost everything (except maybe Far which I couldn't manage to set it up on my Windows).
Probably won't rate this list because each has its merits.

**Comment by babhishek21** [comment]
> (Do people actually use the following for competitive programming?)
> Visual Studio
> Sublime Text
> Atom

I have used all three of these. I have to say Sublime Text is my favourite since I compile and test on the command line anyway. Visual Studio is extremely useful if you are a VC++ and C# fan (TopCoder allows C# and I've heard a few people use Visual Studio for it). Atom is open source and free, but hogs system resources like Chrome.

> I personally have tried everything on this list ....  about almost everything (except maybe **Far** which I couldn't manage to set it up on my Windows).

Far Manager is easy to setup on Windows. Just use it with the highly extensive [ConEmu Console Emulator](https://conemu.github.io).

**Comment by lnishan** [comment]
Thanks for the feedback! Highly appreciated.

ST is almost impeccable in terms of text editing. I can see how it can be great for coding. I had some issues with SublimeGDB (a plugin for GDB Integration) so I wasn't sure.
VS: I see, got it!
Yeah Atom was somewhat laggy. All electron-built apps suffer from similar issues (because of the Chromium core).

Far ... well I think it might have some issues with Windows in Chinese locales. It wasn't displaying windows and characters properly on my computers. I used an locale emulator to make it work iirc.
